### ISSUE TITLE
Zugangsdaten

### ISSUE THREAD

**Issue by Bullnados** [sessl3r/windhager#1]
Schönes Projekt!

Bei meiner Anlage von 2021 und der wWndhager myconnect app funktionieren die Default Daten nicht mehr. Angeblich werden diese überschrieben. Ggf. liegt es auch daran, dass ich ein Softwareupdate der Anlage machen hab lassen (Geht nur indem man mit Windhager direkt in Kontakt tritt.

**Comment by sessl3r** [comment]
Hallo. Vielen Dank.
Das ist erwartet. Von einem anderen Windhager-Nutzer hatte ich erfahren, dass das Default-Passwort bei Nutzung der App geändert wird und man dieses von Windhager auch nicht bekommt. Auch ein Zurücksetzen war wohl völlig undenkbar. Es ist also ein entweder oder.

Einzige Möglichkeit (von mir nicht getestet): Reset des InfoWin Touch (kleiner Taster lange drücken)
Wie gesagt: Von mir nicht getestet und keine Gewähr für das was da passiert (bin mir nicht sicher was die Anleitung sagt).
